[tool.black]
line-length = 999
skip-string-normalization = true
target-version = ['py36']

[tool.isort]
profile = "black"

## https://docs.pytest.org/en/7.1.x/reference/customize.html#pyproject-toml
[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-q --cov=cis_audit --cov-fail-under=100 --cov-report term-missing"
testpaths = [
    "tests/unit/"
]
